[package]
name = "render_gl_derive"
version = "0.1.0"
authors = ["Alagris <alagris@gmail.com>"]
edition = "2018"

[dependencies]
quote = "1.0.9"
syn = "1.0.73"
proc-macro2 = "1.0.27"
[lib]
proc-macro = true
